language: php
php:
  - '8.0'

before_script:
 - composer self-update

install:
 - travis_retry composer install --no-interaction --prefer-source --dev

notifications:
 on_success: never
 on_failure: always