version: '3.9'

networks:
  bedrock:

services:
  web:
    image: nginx:stable-alpine
    volumes:
      - ./:/var/www/html:delegated
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - php
      - mysql
    networks:
      - bedrock
    restart: always

  php:
    container_name: ${APP_NAME}
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
      - ./docker/config/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - 9000:9000
    links:
      - mysql
    environment:
      - WP_CLI_ALLOW_ROOT=true
    networks:
      - bedrock

  mysql:
    container_name: ${APP_NAME}-db
    image: mysql:8
    volumes:
      - ./docker/db:/var/lib/mysql:delegated
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      - bedrock
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    volumes:
      - ./config/phpmyadmin.ini:/usr/local/etc/php/conf.d/phpmyadmin.ini
    ports:
      - 8082:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    networks:
      - bedrock

  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - bedrock
