version: '3.9'

networks:
  bedrock:

services:
  web:
    container_name: kawa-web
    image: nginx:stable-alpine
    volumes:
      - ./:/var/www/html:delegated
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - php
      - mysql
    networks:
      - bedrock

  php:
    container_name: kawa-php
    image: nanoninja/php-fpm:8.0
    volumes:
      - ./:/var/www/html
      - ./docker/config/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - 9000:9000
    networks:
      - bedrock

  composer:
    container_name: kawa-composer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - php
      - web
    networks:
      - bedrock

  wp-cli:
    container_name: kawa-wp-cli
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    links:
      - mysql
    depends_on:
      - php
      - web
      - mysql
    environment:
      - WP_CLI_ALLOW_ROOT=true
    networks:
      - bedrock

  mysql:
    container_name: kawa-db
    image: mysql:8
    volumes:
      - ./docker/db:/var/lib/mysql:delegated
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      - bedrock

  phpmyadmin:
    container_name: kawa-phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    volumes:
      - ./config/phpmyadmin.ini:/usr/local/etc/php/conf.d/phpmyadmin.ini
    ports:
      - 8082:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    networks:
      - bedrock
